### ISSUE TITLE
Option for overriding integrity (shasum) check

### ISSUE THREAD

**Issue by standage** [standage/genhub#74]
Enforce by default, but provide information about override flag upon failure.

**Comment by standage** [comment]
cc @vpbrendel @cycoyuk

New with commit 91ec407:

By default, we get this.

```
$ fidibus --refr=Amel prep 
[GenHub: Apis mellifera] preprocess genome sequence file
[GenHub: Apis mellifera] preprocess annotation file
warning: CDS feature on line 84712 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84713 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84714 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84715 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84716 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84717 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84718 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84719 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84720 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84721 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84722 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84723 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84724 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84725 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84726 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84727 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84728 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84729 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 92167 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 92168 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 92169 in file "stdin" has the wrong phase 2 -> correcting it to 1
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/standage/Software/genhub/scripts/fidibus", line 42, in run_build
    db.prep(strict=not args.relax)
  File "/Users/standage/Software/genhub/genhub/genomedb.py", line 227, in prep
    self.preprocess_gff3(logstream=logstream, verify=verify, strict=strict)
  File "/Users/standage/Software/genhub/genhub/genomedb.py", line 303, in preprocess_gff3
    self.preprocess('gff3', logstream, verify, strict)
  File "/Users/standage/Software/genhub/genhub/genomedb.py", line 290, in preprocess
    raise Exception(message)
Exception: Amel annotation file integrity check failed
d858a1db0fe765955956ef71af832033adf30d35
2db266667ae9a2332522cd8efd9209472661597d

To proceed in spite of this failure, re-run with the `--relax` option enabled.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/standage/Software/genhub/scripts/fidibus", line 228, in <module>
    main(get_parser().parse_args())
  File "/Users/standage/Software/genhub/scripts/fidibus", line 210, in main
    _ = [p.get() for p in results]
  File "/Users/standage/Software/genhub/scripts/fidibus", line 210, in <listcomp>
    _ = [p.get() for p in results]
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
Exception: Amel annotation file integrity check failed
d858a1db0fe765955956ef71af832033adf30d35
2db266667ae9a2332522cd8efd9209472661597d

To proceed in spite of this failure, re-run with the `--relax` option enabled.
```

With new `-x|--relax` mode, we get this.

```
$ fidibus --refr=Amel --relax prep 
[GenHub: Apis mellifera] preprocess genome sequence file
[GenHub: Apis mellifera] preprocess annotation file
warning: CDS feature on line 84712 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84713 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84714 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84715 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84716 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84717 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84718 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84719 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84720 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84721 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84722 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84723 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 84724 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84725 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84726 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84727 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 84728 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 84729 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 92167 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 92168 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 92169 in file "stdin" has the wrong phase 2 -> correcting it to 1
Warning: Amel annotation file integrity check failed
d858a1db0fe765955956ef71af832033adf30d35
2db266667ae9a2332522cd8efd9209472661597d, proceeding anyway
[GenHub: Apis mellifera] preprocess protein sequence file
Warning: Amel protein sequence file integrity check failed
e485036bfe47c69dbeb13e32537cacbb4574c787
7181e4fac161c90d2ee99917afdeac08cd3d9c7b, proceeding anyway
[GenHub: Apis mellifera] build complete!
[GenHub] all builds complete!
```
